language: python
env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -q Django==$DJANGO_VERSION
  - export PYTHONPATH="${PYTHONPATH}:$(realpath mobile_template)"

script:  python example/manage.py test

matrix:
  exclude:
  - python: "3.5"
    env: DJANGO_VERSION=1.7
  - python: "3.5"
    env: DJANGO_VERSION=1.6